plugins:
  - serverless-dynamodb-local
  - serverless-offline
app: sls-test
service: sls-test

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'local'}
  region: eu-central-1
  memorySize: 256
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:eu-central-1:*:*"
  environment:
    TABLE_NAME_USERS: users

custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
  dynamodb:
    stages:
      - ${opt:stage, 'local'}
    start:
      docker: true
      port: 8010
      inMemory: false
      migrate: true
      seed: true
      convertEmptyValues: true
      noStart: true

functions:
  - hello-world:
      handler: handler.hello
      description: "offline example"
      events:
        - http:
            path: hello
            method: GET
  - createUser:
      handler: users.createUser
      events:
        - http:
            path: users/create
            method: PUT

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        GlobalSecondaryIndexes:
          IndexName: isActiveIndex
          KeySchema: 
            - AttributeName: isActive
              KeyType: HASH
            - AttributeName: firstName
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 3
            WriteCapacityUnits: 3
