plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline
app: sls-test
service: sls-test
useDotenv: true
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'local'}
  region: ${env:REGION}
  memorySize: 256
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 'arn:aws:dynamodb:eu-central-1:*:*'
  environment:
    DYNAMO_ENDPOINT: ${env:DYNAMO_ENDPOINT}
    REGION: ${env:REGION}

custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      docker: true
      port: 8010:8000
      inMemory: false
      migrate: true
      convertEmptyValues: false
      noStart: false
      dockerImage: amazon/dynamodb

functions:
  - hello-world:
      handler: handlers/hello/hello.handler
      description: 'offline example'
      events:
        - http:
            path: hello
            method: GET
  - createUser:
      handler: handlers/users/createUser.handler
      events:
        - http:
            path: users/create
            method: PUT
      environment:
        TABLE_NAME_USERS: ${env:TABLE_NAME_USERS}
  - queryUsers:
      handler: handlers/users/queryUsers.handler
      events:
        - http:
            path: users/get
            method: GET
      environment:
        TABLE_NAME_USERS: ${env:TABLE_NAME_USERS}

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: isActive
            AttributeType: N
          - AttributeName: firstName
            AttributeType: S
          - AttributeName: userName
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        GlobalSecondaryIndexes:
          - IndexName: isActiveIndex
            KeySchema:
              - AttributeName: isActive
                KeyType: HASH
              - AttributeName: firstName
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 3
              WriteCapacityUnits: 3
          - IndexName: userNameIndex
            KeySchema:
              - AttributeName: userName
                KeyType: HASH
              - AttributeName: firstName
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 3
              WriteCapacityUnits: 3
